"""An independent forward implementation of the 2D Gaussian pRF pipeline.

Used to generate targets for the fitter *recovery* tests. Those tests assert that a fitter returns
the parameters the data was generated from; if the data is generated by the same model the fitter
wraps, any error in the forward model appears on both sides and cancels, so recovery succeeds
whether or not the model is correct. Generating the target here breaks that circularity.

Only the recovery tests need this. The other fitter tests assert properties of the optimizer --
that gradients reach a parameter, that batched and unbatched agree, that an error path raises -- and
for those, generating data with the model under test is the right choice.

This is written from the definitions, not transcribed from `prfmodel`:

- the receptive field is `scipy.stats.multivariate_normal.pdf` with an isotropic covariance;
- the encoding is a sum over the spatial axes of the receptive field times the design;
- the HRF gammas are `scipy.stats.gamma.pdf` with shape `delay / dispersion` and scale `dispersion`,
  the SPM/nilearn convention pinned in `tests/reference/test_hrf.py`;
- the convolution is `numpy.convolve`, causal, with the response's first sample repeated on the left.

It is not a second source of truth on its own. The same forward path is checked against prfpy and
braincoder in `validation/`, which agree with prfmodel to ~5e-07, so a disagreement between this
module and the package can be arbitrated rather than argued about.

"""

import numpy as np
import pandas as pd
from scipy import stats


def gaussian_receptive_field(grid: np.ndarray, mu_y: float, mu_x: float, sigma: float) -> np.ndarray:
    """Return an isotropic 2D Gaussian receptive field evaluated on `grid`.

    `grid` has shape `(height, width, 2)` and holds `(y, x)` in its last axis, the convention pinned
    by `TestCoordinateConvention` and confirmed against prfpy and braincoder in `validation/`.
    """
    return stats.multivariate_normal.pdf(grid, mean=[mu_y, mu_x], cov=sigma**2 * np.eye(2))


def encode(receptive_field: np.ndarray, design: np.ndarray) -> np.ndarray:
    """Project a receptive field onto a design, giving one value per frame."""
    return np.einsum("hw,thw->t", receptive_field, design)


def hrf_kernel(frames: np.ndarray, params: pd.Series) -> np.ndarray:
    """Return the derivative-of-two-gammas HRF, normalized to unit sum.

    `weight_deriv` of zero reduces this to a plain difference of two gammas. The derivative is taken
    analytically: `d/dt gamma.pdf(t) = gamma.pdf(t) * ((shape - 1) / t - 1 / scale)`.
    """
    shape_1, scale_1 = params["delay"] / params["dispersion"], params["dispersion"]
    shape_2, scale_2 = params["undershoot"] / params["u_dispersion"], params["u_dispersion"]

    density_1 = stats.gamma.pdf(frames, a=shape_1, scale=scale_1)
    density_2 = stats.gamma.pdf(frames, a=shape_2, scale=scale_2)

    derivative_1 = density_1 * ((shape_1 - 1.0) / frames - 1.0 / scale_1)
    derivative_2 = density_2 * ((shape_2 - 1.0) / frames - 1.0 / scale_2)

    kernel = (density_1 - params["ratio"] * density_2) - params["weight_deriv"] * (
        derivative_1 - params["ratio"] * derivative_2
    )

    return kernel / kernel.sum()


def impulse_frames(duration: float = 32.0, resolution: float = 1.0, offset: float = 0.0) -> np.ndarray:
    """Return the time axis the HRF is sampled on, built independently of `BaseImpulse`.

    Each sample sits at the centre of the `resolution`-wide bin it represents, so the axis starts at
    `offset + resolution / 2` and is spaced exactly `resolution` apart, with `duration` acting as an
    upper bound rounded down to whole samples. Sampling at bin centres rather than at their left edges
    keeps `t = 0` off the axis, where the gamma density is undefined for shape parameters below one.
    Deriving this here rather than reading it off the impulse model means a regression in the model's
    sampling grid shows up in the recovery tests too, not only in `tests/reference/test_hrf.py`.
    """
    return (np.arange(int(duration / resolution)) + 0.5) * resolution + offset


def convolve(response: np.ndarray, kernel: np.ndarray) -> np.ndarray:
    """Causal convolution with the first sample repeated on the left, via `numpy.convolve`."""
    pad_len = kernel.size - 1
    padded = np.pad(response, (pad_len, 0), mode="edge")
    return np.convolve(padded, kernel)[pad_len : pad_len + response.size]


def predict(
    stimulus,  # noqa: ANN001 (a PRFStimulus, imported lazily to keep this module dependency-free)
    parameters: pd.DataFrame,
    frames: np.ndarray | None = None,
    *,
    surround: bool = False,
) -> np.ndarray:
    """Predict a BOLD timeseries per unit, independently of `prfmodel`'s model classes.

    Parameters
    ----------
    stimulus
        A `PRFStimulus`; only its `design` and `grid` are read.
    parameters
        One row per unit. Recognized columns are `mu_y`, `mu_x`, `sigma`, `amplitude` and `baseline`,
        the six HRF parameters, and -- when `surround` is set -- the `_center`/`_surround` suffixed
        forms used by the difference-of-Gaussians model.
    frames
        Time axis for the HRF, in seconds. `None` skips the convolution entirely.
    surround
        Build a difference of two Gaussians rather than a single one.

    Returns
    -------
    numpy.ndarray
        Predictions of shape `(num_units, num_frames)`.

    """
    design = np.asarray(stimulus.design, dtype=np.float64)
    grid = np.asarray(stimulus.grid, dtype=np.float64)

    predictions = []

    for _, unit in parameters.iterrows():
        if surround:
            centre = gaussian_receptive_field(grid, unit["mu_y"], unit["mu_x"], unit["sigma_center"])
            around = gaussian_receptive_field(grid, unit["mu_y"], unit["mu_x"], unit["sigma_surround"])
            response = unit["amplitude_center"] * encode(centre, design) - unit["amplitude_surround"] * encode(
                around,
                design,
            )
        else:
            response = encode(gaussian_receptive_field(grid, unit["mu_y"], unit["mu_x"], unit["sigma"]), design)

        if frames is not None:
            response = convolve(response, hrf_kernel(frames, unit))

        if not surround:
            response = unit["amplitude"] * response

        predictions.append(response + unit["baseline"])

    return np.stack(predictions)
