name: Set up Python with pip caching
description: Set up Python, cache pip packages, and install dependencies

inputs:
  python-version:
    description: Python version to install
    required: true
  extras:
    description: Comma-separated pip extras to install (e.g. "dev,tensorflow")
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Python info
      shell: bash -e {0}
      run: |
        which python
        python --version
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
    - name: Upgrade pip and install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install .[${{ inputs.extras }}]
